### ISSUE TITLE
LCS options for curve members

### ISSUE THREAD

**Issue by NextFEM** [StructuralAnalysisFormat/StructuralAnalysisFormat-Doc#212]
Hello,
on this page: https://www.saf.guide/en/stable/structural-analysis-elements/structuralcurvemember.html

the LCS column header is described as an Enum with these possible values:
y by vector
z by vector
y by point
z by point

With reference to "by vector" choices, "y by vector" means that the local y vector has to be supplied?
In [Introduction](https://www.saf.guide/en/stable/getting-started/introduction.html), it is stated that z vector has always to be given.

thanks

**Comment by msalak-scia** [comment]
Hello,
thank you for noticing a mistake and pointing it out. You are right, for 'y by vector', local y vector has to be supplied and local z vector is then defined by the right-hand rule.

In the introduction only 'Z by vector' example is described. We will fix it :)

- [ ] @msalak-scia, in the introduction page in _LCS enum set on “by vector”_, improve description what happens if it is `y by vector` not olny `z by vector`

**Comment by msalak-scia** [comment]
internal reference number 6085

**Comment by msalak-scia** [comment]
We made the changes in the Introduction and closed the issue, they are now in our latest documentation and will be released with the next release of SAF. The latest documentation can be seen here:
https://www.saf.guide/en/latest/getting-started/introduction.html
Thank you again for bringing this to our attention @NextFEM, please let us know if there is anything else we could improve.
